### ISSUE TITLE
I don't know how to contact you so I posted an issue

### ISSUE THREAD

**Issue by tomyahu** [Yozzaxia1311/MegaManLove#7]
Hey @Yozzaxia1311 , first of all sorry for posting an issue for this.

I wanted to talk to you because I'm currently working on a tool to reproduce bugs and glitches that haven't been reproduced since their discovery. I am currently testing the effectiveness of the tool so I was wondering if you have encountered a bug while developing MegaManLove that you haven't been able to reproduce. If I'm able to reproduce it I can give you an input sequence that produces the bug.

Thank you for your time

**Comment by Yozzaxia1311** [comment]
Sorry for the late reply, @tomyahu . I can't think of any tricky bug in my engine, so you won't get much testing here. Thank you, though.
